
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUSASHI NAGASAKI
 */
public class dashboard extends javax.swing.JFrame {
    Connection koneksi = null;
    ResultSet res = null;
    PreparedStatement pst = null;
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        koneksi = KoneksiDatabase.getKoneksi();
        cek();
        dataTampil();
    }
    
    public void cek(){
        login log = new login();
        String level = log.getRole();
        if(!level.equals("admin")){
            anggota.setVisible(false);
            pegawai.setVisible(false);
        }
    }
    
    private void dataTampil(){
        
            Date date = new Date();
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat bulan = new SimpleDateFormat("MM");
            SimpleDateFormat tahun = new SimpleDateFormat("yyyy");
            
        try{

            String bacaData = "SELECT * FROM kunjungan WHERE tgl_kunjungan ='"+formatter.format(date)+"'";
            pst = koneksi.prepareStatement(bacaData,ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_READ_ONLY);
            res = pst.executeQuery();
            res.last();
            pengunjungd.setText(String.valueOf(res.getRow()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        try{
            String bacaData = "SELECT * FROM kunjungan WHERE YEAR(tgl_kunjungan) ='"+tahun.format(date)+"' AND MONTH(tgl_kunjungan) ='"+bulan.format(date)+"'";
            pst = koneksi.prepareStatement(bacaData,ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_READ_ONLY);
            res = pst.executeQuery();
            res.last();
            pengunjungm.setText(String.valueOf(res.getRow()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        try{
            String bacaData = "SELECT * FROM peminjaman WHERE tgl_peminjaman ='"+formatter.format(date)+"'";
            pst = koneksi.prepareStatement(bacaData,ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_READ_ONLY);
            res = pst.executeQuery();
            res.last();
            peminjamd.setText(String.valueOf(res.getRow()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        try{
            String bacaData = "SELECT * FROM peminjaman WHERE YEAR(tgl_peminjaman) ='"+tahun.format(date)+"' AND MONTH(tgl_peminjaman) ='"+bulan.format(date)+"'";
            pst = koneksi.prepareStatement(bacaData,ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_READ_ONLY);
            res = pst.executeQuery();
            res.last();
            peminjamm.setText(String.valueOf(res.getRow()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        try{
            String bacaData = "SELECT * FROM anggota";
            pst = koneksi.prepareStatement(bacaData,ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_READ_ONLY);
            res = pst.executeQuery();
            res.last();
            anggotas.setText(String.valueOf(res.getRow()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        try{
            String bacaData = "SELECT * FROM pegawai";
            pst = koneksi.prepareStatement(bacaData,ResultSet.TYPE_SCROLL_INSENSITIVE, 
                    ResultSet.CONCUR_READ_ONLY);
            res = pst.executeQuery();
            res.last();
            pegawais.setText(String.valueOf(res.getRow()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        buku = new javax.swing.JLabel();
        anggota = new javax.swing.JLabel();
        pegawai = new javax.swing.JLabel();
        peminjaman = new javax.swing.JLabel();
        kunjungan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pegawais = new javax.swing.JLabel();
        pengunjungd = new javax.swing.JLabel();
        pengunjungm = new javax.swing.JLabel();
        peminjamd = new javax.swing.JLabel();
        peminjamm = new javax.swing.JLabel();
        anggotas = new javax.swing.JLabel();
        printPeminjamM = new javax.swing.JLabel();
        printPengunjungM = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setMinimumSize(new java.awt.Dimension(710, 430));
        setPreferredSize(new java.awt.Dimension(720, 470));
        getContentPane().setLayout(null);

        home.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/home.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(10, 120, 120, 18);

        buku.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        buku.setForeground(new java.awt.Color(255, 255, 255));
        buku.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/book.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        buku.setText("BUKU");
        buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuMouseClicked(evt);
            }
        });
        getContentPane().add(buku);
        buku.setBounds(10, 150, 120, 18);

        anggota.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        anggota.setForeground(new java.awt.Color(255, 255, 255));
        anggota.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/user.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        anggota.setText("ANGGOTA");
        anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anggotaMouseClicked(evt);
            }
        });
        getContentPane().add(anggota);
        anggota.setBounds(10, 180, 120, 18);

        pegawai.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        pegawai.setForeground(new java.awt.Color(255, 255, 255));
        pegawai.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/user-secret.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        pegawai.setText("pegawai");
        pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pegawaiMouseClicked(evt);
            }
        });
        getContentPane().add(pegawai);
        pegawai.setBounds(10, 210, 120, 18);

        peminjaman.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        peminjaman.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/inbox.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        peminjaman.setText("peminjaman");
        peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamanMouseClicked(evt);
            }
        });
        getContentPane().add(peminjaman);
        peminjaman.setBounds(10, 240, 120, 18);

        kunjungan.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        kunjungan.setForeground(new java.awt.Color(255, 255, 255));
        kunjungan.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/send.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        kunjungan.setText("kunjungan");
        kunjungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kunjunganMouseClicked(evt);
            }
        });
        getContentPane().add(kunjungan);
        kunjungan.setBounds(10, 270, 120, 18);

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/black/png/24/user-secret.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 240, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Sekolah\\STMIK SUMEDANG\\Semester 3\\PBO\\Font-Awesome-SVG-PNG-master\\Font-Awesome-SVG-PNG-master\\black\\png\\24\\send.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 80, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\Sekolah\\STMIK SUMEDANG\\Semester 3\\PBO\\Font-Awesome-SVG-PNG-master\\Font-Awesome-SVG-PNG-master\\black\\png\\24\\send.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 240, 30, 30);

        jLabel5.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/black/png/24/inbox.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 80, 30, 30);

        jLabel6.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/black/png/24/inbox.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 240, 30, 30);

        jLabel7.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/black/png/24/user.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 80, 30, 30);

        pegawais.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pegawais.setText("1");
        pegawais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pegawais);
        pegawais.setBounds(580, 260, 70, 70);

        pengunjungd.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pengunjungd.setText("1");
        pengunjungd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pengunjungd);
        pengunjungd.setBounds(220, 100, 70, 70);

        pengunjungm.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pengunjungm.setText("1");
        pengunjungm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(pengunjungm);
        pengunjungm.setBounds(220, 260, 60, 70);

        peminjamd.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        peminjamd.setText("1");
        peminjamd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(peminjamd);
        peminjamd.setBounds(410, 100, 70, 70);

        peminjamm.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        peminjamm.setText("1");
        peminjamm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(peminjamm);
        peminjamm.setBounds(400, 260, 70, 70);

        anggotas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        anggotas.setText("1");
        anggotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(anggotas);
        anggotas.setBounds(590, 100, 70, 70);

        printPeminjamM.setIcon(new javax.swing.ImageIcon("E:\\Sekolah\\STMIK SUMEDANG\\Semester 3\\PBO\\Font-Awesome-SVG-PNG-master\\Font-Awesome-SVG-PNG-master\\black\\png\\16\\print.png")); // NOI18N
        printPeminjamM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printPeminjamMMouseClicked(evt);
            }
        });
        getContentPane().add(printPeminjamM);
        printPeminjamM.setBounds(480, 240, 20, 30);

        printPengunjungM.setIcon(new javax.swing.ImageIcon("E:\\Sekolah\\STMIK SUMEDANG\\Semester 3\\PBO\\Font-Awesome-SVG-PNG-master\\Font-Awesome-SVG-PNG-master\\black\\png\\16\\print.png")); // NOI18N
        printPengunjungM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printPengunjungMMouseClicked(evt);
            }
        });
        getContentPane().add(printPengunjungM);
        printPengunjungM.setBounds(300, 240, 20, 30);

        logout.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon("E:\\Sekolah\\STMIK SUMEDANG\\Semester 3\\PBO\\Font-Awesome-SVG-PNG-master\\Font-Awesome-SVG-PNG-master\\white\\png\\16\\sign-out.png")); // NOI18N
        logout.setText("logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(30, 390, 70, 18);

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\Sekolah\\STMIK SUMEDANG\\Semester 3\\PBO\\DesignApps\\dsahboard.jpg")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 710, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        dashboard db = new dashboard();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuMouseClicked
        indexBuku db = new indexBuku();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bukuMouseClicked

    private void anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaMouseClicked
        indexAnggota db = new indexAnggota();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_anggotaMouseClicked

    private void pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pegawaiMouseClicked
        indexPegawai db = new indexPegawai();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pegawaiMouseClicked

    private void peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanMouseClicked
        indexPeminjaman db = new indexPeminjaman();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_peminjamanMouseClicked

    private void kunjunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kunjunganMouseClicked
        // TODO add your handling code here:
        indexKunjungan db = new indexKunjungan();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kunjunganMouseClicked

    private void printPengunjungMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printPengunjungMMouseClicked
        // TODO add your handling code here:
     try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportKunjunganM.jasper"), null, koneksi);
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_printPengunjungMMouseClicked

    private void printPeminjamMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printPeminjamMMouseClicked
     try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportPeminjamanM.jasper"), null, koneksi);
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_printPeminjamMMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login db = new login();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anggota;
    private javax.swing.JLabel anggotas;
    private javax.swing.JLabel buku;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel kunjungan;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel pegawai;
    private javax.swing.JLabel pegawais;
    private javax.swing.JLabel peminjaman;
    private javax.swing.JLabel peminjamd;
    private javax.swing.JLabel peminjamm;
    private javax.swing.JLabel pengunjungd;
    private javax.swing.JLabel pengunjungm;
    private javax.swing.JLabel printPeminjamM;
    private javax.swing.JLabel printPengunjungM;
    // End of variables declaration//GEN-END:variables
}
