
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUSASHI NAGASAKI
 */
public class detailPeminjaman extends javax.swing.JFrame {
    Connection koneksi = null;
    ResultSet res = null;
    PreparedStatement pst = null;
    /**
     * Creates new form insertBuku
     */
    public detailPeminjaman() {
        initComponents();
        koneksi = KoneksiDatabase.getKoneksi();
        cek();
    }
    
    public void cek(){
        login log = new login();
        String level = log.getRole();
        if(!level.equals("admin")){
            anggota.setVisible(false);
            pegawai.setVisible(false);
        }
    }
    
    String ambilIdPeminjaman;
        public String ambilIdPeminjaman(){
            return ambilIdPeminjaman;
        }
    
    public void detailTampil(){
        try{
            String bacaData = "SELECT peminjaman.id_peminjaman AS id_peminjaman, buku.judul AS judul_buku, anggota.nama AS nama_anggota, pegawai.nama AS nama_pegawai, peminjaman.tgl_peminjaman AS tanggal_peminjaman, peminjaman.status AS status_peminjaman, peminjaman.tujuan AS tujuan_peminjaman, peminjaman.tgl_pengembalian AS tanggal_pengembalian from peminjaman JOIN buku ON peminjaman.id_buku=buku.id_buku JOIN anggota ON peminjaman.id_anggota=anggota.id_anggota JOIN pegawai ON peminjaman.id_pegawai=pegawai.id_pegawai WHERE id_peminjaman ="+ambilIdPeminjaman;
            pst = koneksi.prepareStatement(bacaData);
            res = pst.executeQuery();
            if(res.next()){
                juduls.setText(res.getString("judul_buku"));
                anggotas.setText(res.getString("nama_anggota"));
                pegawais.setText(res.getString("nama_pegawai"));
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
                tgl_peminjamans.setText(dateFormat.format(res.getDate("tanggal_peminjaman")));
                Calendar c = Calendar.getInstance();
                c.setTime(res.getDate("tanggal_peminjaman")); 
                c.add(Calendar.DATE, 7);
                tgl_jatuh_tempos.setText(dateFormat.format(c.getTime()));
                statuss.setText(res.getString("status_peminjaman"));
                tujuans.setText(res.getString("tujuan_peminjaman"));
                if(res.getDate("tanggal_pengembalian") == null){
                    tgl_pengembalians.setText("-");
                }else{
                    tgl_pengembalians.setText(dateFormat.format(res.getDate("tanggal_pengembalian")));
                }
                
            String time1 = dateFormat.format(c.getTime());
            String time2 = dateFormat.format(new Date());

            SimpleDateFormat format = new SimpleDateFormat("yyy-MM-dd");
            Date date1 = format.parse(time1);
            Date date2 = format.parse(time2);
            long difference = date2.getTime() - date1.getTime(); 
            long diff = difference / (1000*60*60*24); 
            if(diff <= 0){
                dendas.setText("Rp. 0");
            }else{
                long totalDenda = diff * 2500;
                dendas.setText("Rp. "+totalDenda);
            }
          }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jenis_kelamins = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        juduls = new javax.swing.JLabel();
        anggotas = new javax.swing.JLabel();
        pegawais = new javax.swing.JLabel();
        tgl_peminjamans = new javax.swing.JLabel();
        tujuans = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tgl_pengembalians = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        statuss = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tgl_jatuh_tempos = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dendas = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        buku = new javax.swing.JLabel();
        anggota = new javax.swing.JLabel();
        pegawai = new javax.swing.JLabel();
        peminjaman = new javax.swing.JLabel();
        kunjungan = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 470));
        getContentPane().setLayout(null);

        jLabel2.setText("BUKU :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 100, 130, 14);

        jLabel3.setText("ANGGOTA :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 150, 80, 14);

        jLabel4.setText("PEGAWAI :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 200, 80, 14);

        jLabel5.setText("TGL PEMINJAMAN :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 250, 140, 14);

        jLabel6.setText("TUJUAN PEMINJAMAN:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 100, 140, 14);

        cancel.setBackground(new java.awt.Color(102, 0, 0));
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Kembali");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(489, 350, 180, 23);

        juduls.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        juduls.setText("anggota");
        getContentPane().add(juduls);
        juduls.setBounds(200, 120, 160, 20);

        anggotas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        anggotas.setText("anggota");
        getContentPane().add(anggotas);
        anggotas.setBounds(200, 170, 170, 20);

        pegawais.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pegawais.setText("pegawai");
        getContentPane().add(pegawais);
        pegawais.setBounds(200, 220, 180, 20);

        tgl_peminjamans.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tgl_peminjamans.setText("anggota");
        getContentPane().add(tgl_peminjamans);
        tgl_peminjamans.setBounds(200, 270, 190, 20);

        tujuans.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tujuans.setText("tujuan");
        getContentPane().add(tujuans);
        tujuans.setBounds(400, 120, 270, 20);

        jLabel7.setText("TGL PENGEMBALIAN :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 200, 140, 14);

        tgl_pengembalians.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tgl_pengembalians.setText("tgl_pengembalian");
        getContentPane().add(tgl_pengembalians);
        tgl_pengembalians.setBounds(400, 220, 120, 20);

        jLabel9.setText("STATUS PEMINJAMAN :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 150, 150, 14);

        statuss.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        statuss.setText("status");
        getContentPane().add(statuss);
        statuss.setBounds(400, 170, 240, 20);

        jLabel10.setText("JATUH TEMPO :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 300, 100, 14);

        tgl_jatuh_tempos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tgl_jatuh_tempos.setText("anggota");
        getContentPane().add(tgl_jatuh_tempos);
        tgl_jatuh_tempos.setBounds(200, 320, 170, 20);

        jLabel11.setText("DENDA :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(400, 250, 120, 14);

        dendas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dendas.setText("denda");
        getContentPane().add(dendas);
        dendas.setBounds(400, 270, 110, 20);

        home.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/home.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(10, 120, 120, 18);

        buku.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        buku.setForeground(new java.awt.Color(255, 255, 255));
        buku.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/book.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        buku.setText("BUKU");
        buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuMouseClicked(evt);
            }
        });
        getContentPane().add(buku);
        buku.setBounds(10, 150, 120, 18);

        anggota.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        anggota.setForeground(new java.awt.Color(255, 255, 255));
        anggota.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/user.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        anggota.setText("ANGGOTA");
        anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anggotaMouseClicked(evt);
            }
        });
        getContentPane().add(anggota);
        anggota.setBounds(10, 180, 120, 18);

        pegawai.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        pegawai.setForeground(new java.awt.Color(255, 255, 255));
        pegawai.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/user-secret.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        pegawai.setText("pegawai");
        pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pegawaiMouseClicked(evt);
            }
        });
        getContentPane().add(pegawai);
        pegawai.setBounds(10, 210, 120, 18);

        peminjaman.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        peminjaman.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/inbox.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        peminjaman.setText("peminjaman");
        peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamanMouseClicked(evt);
            }
        });
        getContentPane().add(peminjaman);
        peminjaman.setBounds(10, 240, 120, 18);

        kunjungan.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        kunjungan.setForeground(new java.awt.Color(255, 255, 255));
        kunjungan.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Sekolah/STMIK SUMEDANG/Semester 3/PBO/Font-Awesome-SVG-PNG-master/Font-Awesome-SVG-PNG-master/white/png/16/send.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        kunjungan.setText("kunjungan");
        kunjungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kunjunganMouseClicked(evt);
            }
        });
        getContentPane().add(kunjungan);
        kunjungan.setBounds(10, 270, 120, 18);

        logout.setFont(new java.awt.Font("High Jakarta", 0, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon("E:\\Sekolah\\STMIK SUMEDANG\\Semester 3\\PBO\\Font-Awesome-SVG-PNG-master\\Font-Awesome-SVG-PNG-master\\white\\png\\16\\sign-out.png")); // NOI18N
        logout.setText("logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(30, 390, 70, 18);

        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\Sekolah\\STMIK SUMEDANG\\Semester 3\\PBO\\DesignApps\\Peminjaman.jpg")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 710, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        indexPeminjaman iP = new indexPeminjaman();
        iP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        dashboard db = new dashboard();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuMouseClicked
        indexBuku db = new indexBuku();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bukuMouseClicked

    private void anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaMouseClicked
        indexAnggota db = new indexAnggota();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_anggotaMouseClicked

    private void pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pegawaiMouseClicked
        indexPegawai db = new indexPegawai();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pegawaiMouseClicked

    private void peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanMouseClicked
        indexPeminjaman db = new indexPeminjaman();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_peminjamanMouseClicked

    private void kunjunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kunjunganMouseClicked
        // TODO add your handling code here:
        indexKunjungan db = new indexKunjungan();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kunjunganMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login db = new login();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anggota;
    private javax.swing.JLabel anggotas;
    private javax.swing.JLabel buku;
    private javax.swing.JButton cancel;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JLabel dendas;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jenis_kelamins;
    private javax.swing.JLabel juduls;
    private javax.swing.JLabel kunjungan;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel pegawai;
    private javax.swing.JLabel pegawais;
    private javax.swing.JLabel peminjaman;
    private javax.swing.JLabel statuss;
    private javax.swing.JLabel tgl_jatuh_tempos;
    private javax.swing.JLabel tgl_peminjamans;
    private javax.swing.JLabel tgl_pengembalians;
    private javax.swing.JLabel tujuans;
    // End of variables declaration//GEN-END:variables
}
